#! /bin/bash
cd ~
cp giac-2.0.0/doc/aide_cas /c/xcaswin/aide_cas
cp giac-2.0.0/doc/aide_cas /c/xcaswin/doc/aide_cas
cp giac-2.0.0/doc/fr/xcasmenu /c/xcaswin/doc/fr
rm /c/xcaswin/xcas.rc
#rm giac-2.0.0/src/hist.o
#rm giac-2.0.0/src/usual.o
rm giac-2.0.0/src/xcas.o
cd giac-2.0.0/src
#make
make -f Makefile.w64 xcasdll icasdll 
cp -f xcas.exe icas.exe /c/xcaswin
cp -f giacxcas.dll /c/xcaswin/giacxcas.dll
strip /c/xcaswin/giacxcas.dll
#make -f Makefile.win64 xcasdll icasdll
#cp -f xcas.exe icas.exe giac.dll /c/xcas64
#cp -f icas.exe /c/xcas64/giac.exe
cd ~
/c/NSIS/Unicode/makensis.exe xcaswin.nsi

