[package]
name = "giac-linalg"
description = "Symbolic and numeric linear algebra for giac-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
giac-core = { workspace = true }
giac-poly = { workspace = true }
num-bigint = { workspace = true }
num-integer = { workspace = true }
num-rational = { workspace = true }
num-traits = { workspace = true }
nalgebra = { workspace = true }
