#![deny(unsafe_code)]
//! **API inventory:** inline `/// **Tier**` / `// **Tier**` on every function;
//! full module index in `.doc/giac-groebner-api-stability.md`.
//!

use giac_poly::{Poly, Var};
use num_traits::Zero;

/// Reduce `poly` modulo the ideal generated by `basis` using multivariate division (lex order).
/// **Stable (bounded)** — multivariate reduce mod ideal (lex)
pub fn greduce(poly: &Poly, basis: &[Poly], vars: &[Var]) -> Poly {
    let mut r = poly.clone();
    loop {
        let Some((r_lt, r_lc)) = r.leading_term_lex(vars) else {
            break;
        };
        let mut reduced = false;
        for g in basis {
            if g.is_zero() {
                continue;
            }
            let Some((g_lt, g_lc)) = g.leading_term_lex(vars) else {
                continue;
            };
            if !g_lt.divides(r_lt) {
                continue;
            }
            let Some(q_m) = r_lt.div_exact(g_lt) else {
                continue;
            };
            if g_lc.is_zero() {
                continue;
            }
            let q_c = r_lc.clone() / g_lc.clone();
            let q_term = Poly::term(q_m, q_c);
            r = r.sub(&q_term.mul(g));
            reduced = true;
            break;
        }
        if !reduced {
            break;
        }
    }
    r
}

/// Modular variant (coefficients already reduced mod p).
/// **Stable (bounded)** — reduce PolyMod mod basis
pub fn greduce_mod(poly: &giac_poly::PolyMod, basis: &[giac_poly::PolyMod]) -> giac_poly::PolyResult<giac_poly::PolyMod> {
    let mut r = poly.clone();
    loop {
        let Some((r_lt, r_lc)) = r.leading_term() else {
            break;
        };
        let mut reduced = false;
        for g in basis {
            if g.is_zero() {
                continue;
            }
            let Some((g_lt, g_lc)) = g.leading_term() else {
                continue;
            };
            if !g_lt.divides(r_lt) {
                continue;
            }
            let Some(q_m) = r_lt.div_exact(g_lt) else {
                continue;
            };
            let g_lc_inv = g_lc.inv()?;
            let q_c = r_lc.mul(&g_lc_inv)?;
            let q_term = giac_poly::PolyMod {
                terms: [(q_m, q_c)].into(),
                modulus: r.modulus.clone(),
            };
            r = r.sub(&q_term.mul(g)?)?;
            reduced = true;
            break;
        }
        if !reduced {
            break;
        }
    }
    Ok(r)
}

#[cfg(test)]
mod tests {
    use super::*;
    use giac_poly::PolyMod;
    use num_bigint::BigInt;
    use num_rational::Ratio;

    fn half() -> Ratio<BigInt> {
        Ratio::new(BigInt::from(1), BigInt::from(2))
    }

    #[test]
    fn greduce_xy_minus_1() {
        let x = Poly::var("x");
        let y = Poly::var("y");
        let p = x.mul(&y).sub(&Poly::one());
        let b1 = x.pow(2).sub(&y.pow(2));
        let b2 = x.mul(&y).mul_scalar(&Ratio::from_integer(BigInt::from(2)))
            .sub(&y.pow(2));
        let b3 = y.pow(3);
        let vars = [Var::from("x"), Var::from("y"), Var::from("z")];
        let r = greduce(&p, &[b1, b2, b3], &vars);
        let expected = y.pow(2).mul_scalar(&half()).sub(&Poly::one());
        assert_eq!(r, expected);
    }

    #[test]
    fn greduce_circle() {
        let x = Poly::var("x");
        let y = Poly::var("y");
        let p = x.pow(2).add(&y.pow(2)).sub(&Poly::one());
        let b1 = x.pow(2).sub(&y.pow(2));
        let b2 = x.mul(&y).mul_scalar(&Ratio::from_integer(BigInt::from(2)))
            .sub(&Poly::one());
        let vars = [Var::from("x"), Var::from("y")];
        let r = greduce(&p, &[b1, b2], &vars);
        let expected = y.pow(2).mul_scalar(&Ratio::from_integer(BigInt::from(2)))
            .sub(&Poly::one());
        assert_eq!(r, expected);
    }

    #[test]
    fn greduce_mod_linear() {
        let modulus = BigInt::from(13);
        let x = Poly::var("x");
        let p = PolyMod::from_poly(&x.pow(2).sub(&Poly::one()), modulus.clone()).unwrap();
        let d = PolyMod::from_poly(&x.sub(&Poly::one()), modulus.clone()).unwrap();
        let r = greduce_mod(&p, &[d]).unwrap();
        assert!(r.is_zero());
    }
}
